### ISSUE TITLE
Automatic updating broken?

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap-Documentation#7]
Updates of 4 days ago haven't shown up yet on carnap.io.

**Comment by gleachkr** [comment]
OK. I think the issue was that the update script used an environment variable that the cron process didn't have available. I've fixed that, so hopefully it will work now. I did a manual update of the docs in the process (to make sure that the script was working), but we should check later to see if automatic updates are going through.

**Comment by rzach** [comment]
Seems to work!

**Comment by rzach** [comment]
Oh wait no I think it doesn't. In any case, changes from 2 days ago aren't yet on the carnap side eg https://carnap.io/srv/doc/systems.md

**Comment by gleachkr** [comment]
OK, I think I missed this in the [run-parts manual](https://www.unix.com/man-page/Linux/8/RUN-PARTS/
):

>  If neither the --lsbsysinit option nor the --regex option is given then the names must consist entirely of ASCII upper- and lower-case letters, ASCII digits, ASCII underscores, and ASCII minus-hyphens.

So, in a breathtaking triumph of program design, a utility for running scripts will ignore everything with an `.sh` suffix.

I've set it to run hourly now, so we should know whether it's working once lunchtime is over.

**Comment by gleachkr** [comment]
OK, verified working.
